### ISSUE TITLE
JSR high byte issue

### ISSUE THREAD

**Issue by essial** [TomHarte/ProcessorTests#36]
I'm working on a 6502 based emulator, and have gotten through 74,044 tests so far, but having a strange issue with a JSR test.
I'm getting the following test failure:
```
Error for test (74044): 20 55 13

Instruction: JSR Absolute

Expected PC to be 0155, got 1355 for test 20 55 13
Initial state:
{"pc":379,"s":125,"a":158,"x":137,"y":52,"p":230,"ram":[[379,32],[380,85],[381,19],[341,173]]}

Final state:
{"pc":341,"s":123,"a":158,"x":137,"y":52,"p":230,"ram":[[341,173],[379,32],[380,125],[381,1]]}

Actual state:
PC:$1355  A:$9E  X:$89  Y:$34  SP:$7B  Flags:[NV-UbdIZc]

RAM Setup:
$017B: $20
$017C: $55
$017D: $13
$0155: $AD

Expected Bus Operations:

[379,32,"read"]
[380,85,"read"]
[381,19,"read"]
[381,1,"write"]
[380,125,"write"]
[381,1,"read"]
```
It looks like the test is expecting the JSR to disregard the high byte (or keep the same one). Is there some strange JSR or absolute addressing bug that I'm not aware of? Or am I doing something dumb in my emulator.

What it wants the PC to be at: `0x017B (379)`
What it is in my emulator: `0x1355 (4949)`

You can see that it reads the opcode ($20), then low byte of destination $55, then the destination high byte $13. This gives a total destination of $1355. The fact that it's jumping to $0155 makes it obvious its expecting to discard the high byte of the jump instruction, but I cannot find information anywhere online to explain what edge case would cause this wrap.

For now I've updated the test to have an expected PC of 4949.

**Comment by TomHarte** [comment]
This definitely puzzled me, but I think I've figured it out: the stack is stomping upon the instruction mid-flight.

The cycle breakdown for JSR per [64doc](https://github.com/ahefner/tenes/blob/master/tech/64doc.txt) is:

        1    PC     R  fetch opcode, increment PC
        2    PC     R  fetch low address byte, increment PC
        3  $0100,S  R  internal operation (predecrement S?)
        4  $0100,S  W  push PCH on stack, decrement S
        5  $0100,S  W  push PCL on stack, decrement S
        6    PC     R  copy low address byte to PCL, fetch high address
                       byte to PCH

So in this case:

PC is initially 0x17B; S is initially 0x7D so the stack pointer is currently at 0x17D.

1. fetch opcode from 0x17b, which is 0x20;
2. fetch low byte of target address from 0x17c, which is 0x55;
3. read from the stack, by coincidence address 0x17d, doing absolutely nothing with the result;
4. write the current high byte of the PC, which is value 1, to the stack at 0x17d;
5. write the current low byte of the PC, which is 0x7d, to the stack at 0x17c;
6. fetch high byte of target address from 0x17d, which is now 1, because it was written there back in cycle 4.

**Comment by essial** [comment]
WAIT. Wow. This test is executing instructions INSIDE of the stack. I didn't even think about that!

This is both the best and worst test ever written.

You, my friend, have won the internet.

**Comment by essial** [comment]
Just to follow up, I implemented that order of operation and that passed the test, thank you so much!

```java
        var addressLow = readByte();
        pushWord(state.pc);
        var addressHigh = readByte();
        state.pc = (addressHigh << 8) | addressLow;
```
